name: jstocks-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.*
  - pytorch-cuda=11.8  # ※ GPU 環境用。CPU 環境の場合は削除してください。
  - pytorch-lightning=2.1.*
  - scikit-learn
  - pandas
  - matplotlib
  - numpy
  - catboost
  - pip
  - pip:
      - pytorch-forecasting>=1.3.0
      